### PR TITLE
Allow specifying different http readiness host

### PR DESCRIPTION
**Pull request by kubehe**
### :pencil: Description

In some deployments I have rest only application.
In those cases healthcheck probe is on http and app serving traffic on https (different ports, but this already works fine).
In those cases I cannot warmup application with current setup.

Allowing to specify different http host for readiness would solve my issue.

### :link: Related Issues

[https://github.com/ExpediaGroup/mittens/issues/254](https://github.com/ExpediaGroup/mittens/issues/254)

### CODE REVIEW

**Comment by nikos912000** [comment]
Thanks for the PR @kubehe. It looks good to me.
@worldtiki thoughts?

**Comment by worldtiki** [comment]
I was planning to remove the existing `-target-http-host` and just hardcode it to localhost since developers who are unfamiliar with k8s may accidentally set this to "http://service.namespace" which will have unintended effects.

I wonder if we can, either as part of this pr or a separate one, drop the ability to set the host, and replace the existing flags with one where users just set the protocol (http or https), for both the warmup phase and for the readiness probes.

Thoughts?

**Comment by nikos912000** [comment]
> I was planning to remove the existing `-target-http-host` and just hardcode it to localhost since developers who are unfamiliar with k8s may accidentally set this to "http://service.namespace" which will have unintended effects.
> 
> I wonder if we can, either as part of this pr or a separate one, drop the ability to set the host, and replace the existing flags with one where users just set the protocol (http or https), for both the warmup phase and for the readiness probes.
> 
> Thoughts?

Unfortunately the host will not necessarily be `localhost`. When running mittens as a linked container on Docker for Windows/Mac it might need to be set to `host.docker.internal`.

**Comment by kubehe** [comment]
I agree with @nikos912000 

Removing host flag potentially makes it harder to test out locally with containers.
I would prefer to keep this option.

**Review by worldtiki — APPROVED** [review]

**Pull request merged**
