### PR TITLE
issue #175 : add negative test of toHTTPRequests function

### PR DESCRIPTION
**Pull request by rendyreivaldy25**
### :pencil: Description
Add negative tests of toHTTPRequests function :
1. when http methods is wrong
2. when the format is wrong
3. when the file is not exist

### :link: Related Issues
#175

### CODE REVIEW

**Comment by nikos912000** [comment]
Hi @rendyreivaldy25 
Thanks for the contribution :)

We have someone from my team working on this. As she's not part of our GitHub team I assigned this to myself to make it clear it's been assigned.

I'd give priority to the person that is working on it already :)

**Comment by rendyreivaldy25** [comment]
okay, I didn't notice because I think this is an open issue. thank you for the information.

**Comment by nikos912000** [comment]
Hi @rendyreivaldy25 
As discussed, this was implemented in https://github.com/ExpediaGroup/mittens/pull/181. Apologies if the open issue caused confusion.
Is it ok to close this PR?

**Comment by rendyreivaldy25** [comment]
Yes go ahead. Don't mind me. Thank you

**Pull request closed without merging**
