### PR TITLE
Add FetchAuthToken functionality

### PR DESCRIPTION
**Pull request by esikgabi**
### :pencil: Description
Add functionality to fetch an Authentication Token and set it up into the Authorization HTTP header.
Two new parameters are added:
 - fetch-auth-token (boolean) to enable this new feature
 - target-auth-token-path (string) to override the default "/mittens/token" path where the token will be fetched

The functionality is located after the RedinessProbe is successful so we can call the target app.
When the token fetch cannot be possible the HTTP headers are not extended and the error message is logged.
New SendAuthTokenRequest is created in the client.go for handling this type of HTTP request where the response body is used.

Based on the issue (which is mentioned below) and my own experiences some solution is needed for warming up those code parts in the target app which are located behind authentication.
Usually, the target app is able to create or generate a valid AuthToken. It is typically needed for local run/test or smoke/integration tests. The task of the target app developer is only to publish this token generation result via a simple REST endpoint. This token should be generated only one time with short-live mode. In this way, it cannot be used later.
I know it is not a full authentication module but it can help a lot of teams.

Mittens-Fetch-Token drawio

### :link: Related Issues
https://github.com/ExpediaGroup/mittens/issues/190

### CODE REVIEW

**Comment by worldtiki** [comment]
how would this token endpoint work?
maybe an alternative would be to inject credentials as k8s secrets and them use them against a login endpoint to obtain a valid token

**Comment by esikgabi** [comment]
> how would this token endpoint work? maybe an alternative would be to inject credentials as k8s secrets and them use them against a login endpoint to obtain a valid token

Hi [Daniel Albuquerque](https://github.com/worldtiki),
You are absolutely right and it can be implemented in a second/third phase. 
Configuring and implementing the login and token generation service calls in the Mittens requires a bit more time and effort.
This change just offers a solution till the mentioned solution is implemented. After full implementation, these parameters and functions can be removed.

As I mentioned, typically the target side has a solution to generate tokens (for local tests or smoke/integration tests).
The developers just publish this token generation mechanism via a rest endpoint for mittens.
I used a simple spring app (as a target) during my test which has a method in a rest controller:
`@GetMapping("/mittens/token")
public String token(){
	return "JzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpva";
}`

It is not a full and final solution, but a solution which helps a lot of developers.

**Comment by worldtiki** [comment]
> Hi [Daniel Albuquerque](https://github.com/worldtiki), You are absolutely right and it can be implemented in a second/third phase. Configuring and implementing the login and token generation service calls in the Mittens requires a bit more time and effort. This change just offers a solution till the mentioned solution is implemented. After full implementation, these parameters and functions can be removed.
> 
> As I mentioned, typically the target side has a solution to generate tokens (for local tests or smoke/integration tests). The developers just publish this token generation mechanism via a rest endpoint for mittens. I used a simple spring app (as a target) during my test which has a method in a rest controller: `@GetMapping("/mittens/token") public String token(){ return "JzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpva"; }`
> 
> It is not a full and final solution, but a solution which helps a lot of developers.

Thanks for the reply.

As it stands, this would not be used in a production environment which is the environment where Mittens is usually needed.

I'd like to hear a few more opinions to decide, but if this was to be merged I think we should make it clear that it's an alpha feature with no backwards compatibility guarantees in the next iteration.

**Comment by esikgabi** [comment]
> > Hi [Daniel Albuquerque](https://github.com/worldtiki), You are absolutely right and it can be implemented in a second/third phase. Configuring and implementing the login and token generation service calls in the Mittens requires a bit more time and effort. This change just offers a solution till the mentioned solution is implemented. After full implementation, these parameters and functions can be removed.
> > As I mentioned, typically the target side has a solution to generate tokens (for local tests or smoke/integration tests). The developers just publish this token generation mechanism via a rest endpoint for mittens. I used a simple spring app (as a target) during my test which has a method in a rest controller: `@GetMapping("/mittens/token") public String token(){ return "JzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikpva"; }`
> > It is not a full and final solution, but a solution which helps a lot of developers.
> 
> Thanks for the reply.
> 
> As it stands, this would not be used in a production environment which is the environment where Mittens is usually needed.
> 
> I'd like to hear a few more opinions to decide, but if this was to be merged I think we should make it clear that it's an alpha feature with no backwards compatibility guarantees in the next iteration.

The goal is we can use this in production. The target apps should implement a /mittens/token GET endpoint which is called by the mittens. This endpoint will provide a valid (short live) token for mittens for tests.
I tried to summarise it in here: https://github.com/esikgabi/mittens/blob/main/docs/about/getting-started.md#auth-token-fetch-from-target

If you like I can add a "(Alpha)" postfix after this paragraph name.

I only mentioned the local/smoke/integration tests as an example where a token generation exists and developers can move/copy it to the application /mittens/token endpoint for mittens. This endpoint will part of the application so mittens can call it on production also. The most important is we can use it in production.

**Comment by nikos912000** [comment]
Hi Gabor. Thanks for raising the PR.

A few comments:
- Unless I am missing something, wouldn't having an endpoint that returns the token in the application defeat the purpose of having (JWT) tokens in the first place?
- By passing the token as a header we open mittens to a man-in-the-middle attack. One can intercept the request and get that token. For this we should make it clear that communication between containers should be over a secure channel and use a secure storage mechanism (e.g. Kubernetes secret) to store the token instead of passing it in the HTTP headers. Then, the main container will be reading the token from the (secure) storage.

**Comment by esikgabi** [comment]
> Hi Gabor. Thanks for raising the PR.
> 
> A few comments:
> 
> * Unless I am missing something, wouldn't having an endpoint that returns the token in the application defeat the purpose of having (JWT) tokens in the first place?
> * By passing the token as a header we open mittens to a man-in-the-middle attack. One can intercept the request and get that token. For this we should make it clear that communication between containers should be over a secure channel and use a secure storage mechanism (e.g. Kubernetes secret) to store the token instead of passing it in the HTTP headers. Then, the main container will be reading the token from the (secure) storage.

Hi Nikos,
Thanks for your comments.
The endpoint which supports the token should be implemented by the target app's dev. The mittens just tries to call it if the required parameter is set.
The man-in-the-middle attack is a valid problem. Maybe we can document it on the web page and we can print a warning message during startup when this option is enabled.
- The communication between target and mittens pods is only HTTP the secure (HTTPS) layer is handled in a separate container or an upper level (sidecar-proxy, service mash). I do not think we can change this.
- The Authentication related info is usually transferred in headers I do not think we can force the target app's developers to fetch the auth info from another place when the client is mittens.

As I mentioned earlier the target app's developer responsible for this token endpoint generates a less-risky token when possible. For example: 
- short live token (e.g.: 3 mins) which is valid only during the test
- specific and dedicated (user) token for mittens with limited permissions

**Comment by worldtiki** [comment]
There is nothing preventing someone else to abuse the test token. As it is, this is a security risk and I don't think we should be promoting these practices.
Thank you for the contribution @esikgabi but I'll have to decline the pr.

**Comment by esikgabi** [comment]
> There is nothing preventing someone else to abuse the test token. As it is, this is a security risk and I don't think we should be promoting these practices. Thank you for the contribution @esikgabi but I'll have to decline the pr.

Hi @worldtiki,
I can accept your decision.
Is there any plan/idea of how the authentication required code could be warmed-up with mittens?
Fetching tokens from outside can be replaced with a solution where authorization and token service are called by mittens.
But we only have HTTP protocol between mittens and the target app. 
Is it acceptable to send auth-token via HTTP headers when the token is generated by mittens?
Thanks

**Pull request closed without merging**
